### ISSUE TITLE
step5 make error

### ISSUE THREAD

**Issue by liyongjun123** [cj1128/tiny-x64-helloworld#1]
tiny-x64-helloworld/step5$ make
gcc hello.c -s -O3 -e nomain -nostartfiles -nostdlib -T link.lds -o hello.out
`str' referenced in section `.text' of /tmp/cciCzuEw.o: defined in discarded section `.data.rel.local' of /tmp/cciCzuEw.o
`str' referenced in section `.text' of /tmp/cciCzuEw.o: defined in discarded section `.data.rel.local' of /tmp/cciCzuEw.o
collect2: error: ld returned 1 exit status
make: *** [Makefile:2：build] 错误 1

**Comment by cj1128** [comment]
这个问题是编译器版本不同默认生成了一些其他的 Section，我的链接脚本 `link.lds` 中只保留了 `.text`, `.data` 和 `.rodata*`，将报错的 Section 加入链接脚本中就行了。

你复制的错误消息格式有点乱了，看不太清楚，应该改成这样就行了 `tiny : { *(.text) *(.data*) *(.rodata*) }`。
